componentsの下にtoolbarコンポーネントを作成した。
mameccof/intern-book-app pull request #19
Opened 2022-04-08 10:03 UTC by mameccof

app.componentに変更を加え、表示ができるようにした。

## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

## ⛏ 変更内容 / Details of Changes

- toolbarを作成した
- app.componentの変更

## 📸 スクリーンショット / Screenshots

## レビューするポイント (Points for review):

 - toolbarを表示できる

2022-04-08 10:13 UTC, hikaru-nakamura-thedott requested changes
一箇所だけ気になりましたー

2022-04-08 10:13 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/components/toolbar/toolbar.component.css
> +.library{
toolbar.component.cssに書いたスタイルはtoolbar.component.htmlだけに適用されるようになってます！
なので、後で読む人（未来の自分）が「ん？なんでここにクラス指定してるんだ？」と混乱しないように、toolbar.component.htmlで使わないクラスは削除してあげましょう！

2022-04-08 10:13 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/app.module.ts
> -
いらない行の削除いいですね！
空行の入れ方もソースを読みやすくするテクニックの一つです！

2022-04-11 08:47 UTC, kusanoshunsuke approved these changes

2022-04-11 08:48 UTC, merged