Feature/10
mameccof/intern-book-app pull request #23
Opened 2022-04-19 12:22 UTC by mameccof

## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #0
- #0

## ⛏ 変更内容 / Details of Changes

- ngmodelを追加

## 📸 スクリーンショット / Screenshots

## レビューするポイント (Points for review):

 - 書籍の追加をすると一覧に表示されること

2022-04-20 09:26 UTC, hikaru-nakamura-thedott requested changes
アドバイスと修正箇所ありましたー

2022-04-20 09:26 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.ts
> +  addBook(): void{
素晴らしいチャレンジですね！

吉田くんの言う通り、if文のネストが気になるところですね！
回避する方法としては、「値が正しくないときはalertだしてreturnさせる」を繰り返すといいですよ！

```javascript
if(this.tmpBook.name === '' || this.tmpBook.detail === '' || this.tmpBook.evaluation === ''){
  alert("全てのデータを入力してください");
  return;
}
```

2022-04-20 09:26 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.ts
> +        if(this.tmpBook.evaluation < 100 && this.tmpBook.evaluation >= 0){
`this.tmpBook.evaluation < 100` だと100が入らないよ！

2022-04-20 09:26 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.ts
> +  //bookListにデータを追加すれば良いと考える＞入力されたデータを一時的に保持する変数をさくせい＞ボタンが押された時にaddDataを実行してbookListにデータを突っ込めばいいと思った。
ナイスコメント 👍

2022-04-20 09:43 UTC, mameccof commented on intern-book-app/src/app/pages/list/list.component.ts
> +        if(this.tmpBook.evaluation < 100 && this.tmpBook.evaluation >= 0){
修正しました！

2022-04-20 09:45 UTC, mameccof commented on intern-book-app/src/app/pages/list/list.component.ts
> +  addBook(): void{
数字にeを入れて一つづつifで判定させるとe>100やe<0をすることになるんですが、これってエラーにつながったりしますか？

2022-04-20 09:46 UTC, hikaru-nakamura-thedott requested changes
ごめんねー、エラー表示のところこっちの方が綺麗かも〜

2022-04-20 09:46 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.html
> +        <input matInput placeholder="書籍名" type="text" [(ngModel)]="tmpBook.name">
さっきのレビューで言えればよかったんですけど、入力必須の場合はrequiredを付けるといいですよ！
これを付けると表示がいい感じになるんで、僕が指示してcssに書いたinput:invalid消してみてみてくださいー。

```
<input matInput placeholder="書籍名" type="text" [(ngModel)]="tmpBook.name" required>
```

<img width="494" alt="スクリーンショット 2022-04-20 18 43 34" src="https://user-images.githubusercontent.com/86763776/164200308-0c14b009-bda3-444c-971a-5b95649de5f2.png">

他二つのinput, textareaも同様ですー。

2022-04-20 09:46 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.css
> +input:invalid{
評価点のinputタグの挙動確認したくて入れたんだけど、materialの表示の方が綺麗だから、削除しちゃった方が綺麗に表示されるかも〜。
いらない行追加させちゃってごめんねー

2022-04-20 09:49 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.ts
> +  addBook(): void{
そうですねー。文字列と比較するのは良くないですね〜。
チェックする順番を変えてはどうでしょうか？
以下のようにすれば、e<100という比較が起こることは無くなると思います！

1. 空文字チェック
2. 数字チェック(数字かどうか)
3. 数値チェック(0~100か)

2022-04-21 02:35 UTC, hikaru-nakamura-thedott approved these changes
OKでーす。マージしまーす。

2022-04-21 02:36 UTC, merged